import PDFDocument from "pdfkit";

export const PdfService = {
  /**
   * Generates a PDF from a report text and returns a buffer
   */
  async generateReportPdf(reportId, reportType, aiContent) {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 50 });
        const buffers = [];

        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => {
          const pdfData = Buffer.concat(buffers);
          resolve(pdfData);
        });

        // Executive MindHeal Report Design
        doc.rect(0, 0, doc.page.width, 12).fill('#319795'); // Top accent bar

        doc.fillColor('#2D3748').fontSize(22).font('Helvetica-Bold').text(`MindHeal Psychological Wellness Platform`, 50, 40, { align: 'left' });
        doc.fillColor('#718096').fontSize(12).font('Helvetica').text(`AI Self-Reflection & Clinical Analysis Report`, 50, 68, { align: 'left' });
        doc.moveDown(1.5);

        // Metadata Box
        const startY = 100;
        doc.rect(50, startY, doc.page.width - 100, 50).fillAndStroke('#F7FAFC', '#E2E8F0');
        doc.fillColor('#2D3748').fontSize(10).font('Helvetica-Bold')
           .text(`Report Reference ID: ${reportId}`, 65, startY + 12)
           .text(`Analysis Category: ${reportType.toUpperCase()}`, 65, startY + 28);
        doc.fillColor('#718096').font('Helvetica')
           .text(`Generated On: ${new Date().toLocaleDateString('en-IN', { dateStyle: 'full' })}`, doc.page.width - 250, startY + 12);

        doc.moveDown(4);
        doc.fillColor('#2D3748').fontSize(14).font('Helvetica-Bold').text(`Executive Summary & Analysis`, 50);
        doc.moveDown(0.5);

        doc.fillColor('#4A5568').fontSize(11).font('Helvetica').text(aiContent, {
          align: 'left',
          lineGap: 5
        });

        doc.moveDown(2);
        // Disclaimer & Branding Footer
        doc.rect(50, doc.page.height - 70, doc.page.width - 100, 30).fill('#EDF2F7');
        doc.fillColor('#718096').fontSize(8).font('Helvetica-Oblique')
           .text(`Confidential: This report is generated by MindHeal AI for self-reflection and personal wellness. It does not constitute formal medical diagnosis or psychiatric prescription.`, 60, doc.page.height - 62, { width: doc.page.width - 120, align: 'center' });

        doc.end();
      } catch (err) {
        reject(err);
      }
    });
  }
};
