import fs from 'fs';

const filePath = '/Users/designerdharm/Public/psychology website/src/utils/i18n.js';
let content = fs.readFileSync(filePath, 'utf8');

const enKeys = `\n    "Simple Process": "Simple Process",
    "Choose Your Path": "Choose Your Path",
    "Start a free session with our clinical AI, or browse our directory of human experts.": "Start a free session with our clinical AI, or browse our directory of human experts.",
    "Begin Healing": "Begin Healing",
    "Use the CBT diary, take psych tests, and track your mood daily to see real progress.": "Use the CBT diary, take psych tests, and track your mood daily to see real progress.",
    "For Professionals": "For Professionals",
    "Join India's Top Network of Mental Health Experts": "Join India's Top Network of Mental Health Experts",
    "Expand your practice, manage appointments seamlessly, and help thousands of users on MindHeal. Our streamlined onboarding takes less than 10 minutes.": "Expand your practice, manage appointments seamlessly, and help thousands of users on MindHeal. Our streamlined onboarding takes less than 10 minutes.",
    "Sign Up as Counsellor": "Sign Up as Counsellor",
    "Quick Onboarding": "Quick Onboarding",
    "Verify your RCI credentials and set your availability instantly.": "Verify your RCI credentials and set your availability instantly.",
    "Smart Scheduling": "Smart Scheduling",
    "Manage bookings and reminders with our built-in calendar.": "Manage bookings and reminders with our built-in calendar.",
    "Grow Your Practice": "Grow Your Practice",
    "Get connected with users actively seeking your expertise.": "Get connected with users actively seeking your expertise.",
    "Real People. Real Healing.": "Real People. Real Healing.",
    "Average App Rating": "Average App Rating",
    "Messages Exchanged": "Messages Exchanged",
    "Report Reduced Anxiety": "Report Reduced Anxiety",
    "I struggled with severe anxiety for years. The CBT tools and my therapist on MindHeal completely changed my life.": "I struggled with severe anxiety for years. The CBT tools and my therapist on MindHeal completely changed my life.",
    "The AI companion is incredible for late-night panic attacks. It grounds me instantly.": "The AI companion is incredible for late-night panic attacks. It grounds me instantly.",
    "Finally, a platform that understands Indian cultural context. My therapist here gets exactly what I mean without me over-explaining.": "Finally, a platform that understands Indian cultural context. My therapist here gets exactly what I mean without me over-explaining.",
    "Know Thyself": "Know Thyself",
    "12 Free Clinical Tests.": "12 Free Clinical Tests.",
    "Available Assessments": "Available Assessments",
    "PHQ-9 (Depression)": "PHQ-9 (Depression)",
    "Patient Health Questionnaire": "Patient Health Questionnaire",
    "Standardized clinical assessment for depression severity.": "Standardized clinical assessment for depression severity.",
    "GAD-7 (Anxiety)": "GAD-7 (Anxiety)",
    "Generalized Anxiety Disorder Assessment": "Generalized Anxiety Disorder Assessment",
    "Standardized clinical assessment for anxiety severity.": "Standardized clinical assessment for anxiety severity.",
    "Adult ADHD (ASRS)": "Adult ADHD (ASRS)",
    "Adult ADHD Self-Report Scale": "Adult ADHD Self-Report Scale",
    "Screening tool for Attention Deficit Hyperactivity Disorder.": "Screening tool for Attention Deficit Hyperactivity Disorder.",
    "PTSD Checklist (PCL-5)": "PTSD Checklist (PCL-5)",
    "PTSD Checklist for DSM-5": "PTSD Checklist for DSM-5",
    "Clinical assessment for Post-Traumatic Stress Disorder.": "Clinical assessment for Post-Traumatic Stress Disorder.",
    "Bipolar Spectrum": "Bipolar Spectrum",
    "Mood Disorder Questionnaire": "Mood Disorder Questionnaire",
    "Screening tool for bipolar spectrum disorders.": "Screening tool for bipolar spectrum disorders.",
    "OCD Screening": "OCD Screening",
    "Obsessive-Compulsive Inventory": "Obsessive-Compulsive Inventory",
    "Assessment for symptoms of Obsessive-Compulsive Disorder.": "Assessment for symptoms of Obsessive-Compulsive Disorder.",
    "Attachment Style": "Attachment Style",
    "Experiences in Close Relationships": "Experiences in Close Relationships",
    "Assessment of adult attachment styles in relationships.": "Assessment of adult attachment styles in relationships.",
    "Burnout Inventory": "Burnout Inventory",
    "Maslach Burnout Inventory": "Maslach Burnout Inventory",
    "Standardized measure of occupational burnout.": "Standardized measure of occupational burnout.",
    "Self-Esteem Index": "Self-Esteem Index",
    "Rosenberg Self-Esteem Scale": "Rosenberg Self-Esteem Scale",
    "Measure of global self-worth and self-esteem.": "Measure of global self-worth and self-esteem.",
    "Anger Management": "Anger Management",
    "Buss-Perry Aggression Questionnaire": "Buss-Perry Aggression Questionnaire",
    "Clinical measure of aggressive and angry behavior.": "Clinical measure of aggressive and angry behavior.",
    "Relationship Satisfaction": "Relationship Satisfaction",
    "Couples Satisfaction Index": "Couples Satisfaction Index",
    "Measure of satisfaction in romantic relationships.": "Measure of satisfaction in romantic relationships.",
    "Sleep Quality": "Sleep Quality",
    "Pittsburgh Sleep Quality Index": "Pittsburgh Sleep Quality Index",
    "Clinical assessment of sleep quality and patterns.": "Clinical assessment of sleep quality and patterns.",
    "Question": "Question",
    "of": "of",
    "Over the last 2 weeks": "Over the last 2 weeks",
    "Not at all": "Not at all",
    "Several days": "Several days",
    "More than half the days": "More than half the days",
    "Nearly every day": "Nearly every day",
    "Minimal Depression": "Minimal Depression",
    "Mild Depression": "Mild Depression",
    "Moderate Depression": "Moderate Depression",
    "Moderately Severe Depression": "Moderately Severe Depression",
    "Severe Depression": "Severe Depression",
    "Minimal Anxiety": "Minimal Anxiety",
    "Mild Anxiety": "Mild Anxiety",
    "Moderate Anxiety": "Moderate Anxiety",
    "Severe Anxiety": "Severe Anxiety",
    "Premium Assessment": "Premium Assessment",
    "Create a free account to unlock this clinical assessment and track your results.": "Create a free account to unlock this clinical assessment and track your results.",
    "Unlock Assessment": "Unlock Assessment",
    "Assessment Complete": "Assessment Complete",
    "This is a screening tool, not a diagnosis. To discuss these results, please consult a clinical psychologist.": "This is a screening tool, not a diagnosis. To discuss these results, please consult a clinical psychologist.",
    "Discuss with a Counsellor": "Discuss with a Counsellor",
    "Retake Assessment": "Retake Assessment",
    "The Top 1%": "The Top 1%",
    "Meet Your Match.": "Meet Your Match.",
    "All Experts": "All Experts",
    "Clinical Psychologists": "Clinical Psychologists",
    "Trauma Specialists": "Trauma Specialists",
    "Relationship Counsellors": "Relationship Counsellors",
    "Child Psychologists": "Child Psychologists",
    "Book": "Book",
    "12+ Years Exp": "12+ Years Exp",
    "8+ Years Exp": "8+ Years Exp",
    "5+ Years Exp": "5+ Years Exp",
    "15+ Years Exp": "15+ Years Exp",
    "CLINICAL PSYCHOLOGIST": "CLINICAL PSYCHOLOGIST",
    "RELATIONSHIP COUNSELLOR": "RELATIONSHIP COUNSELLOR",
    "TRAUMA SPECIALIST": "TRAUMA SPECIALIST",
    "CHILD PSYCHOLOGIST": "CHILD PSYCHOLOGIST",
    "Sign up instantly. Your data is encrypted and completely confidential.": "Sign up instantly. Your data is encrypted and completely confidential.",
    "Feeling nervous, anxious, or on edge?": "Feeling nervous, anxious, or on edge?",
    "Not being able to stop or control worrying?": "Not being able to stop or control worrying?",
    "Worrying too much about different things?": "Worrying too much about different things?",
    "Trouble relaxing?": "Trouble relaxing?",
    "Being so restless that it is hard to sit still?": "Being so restless that it is hard to sit still?",
    "Becoming easily annoyed or irritable?": "Becoming easily annoyed or irritable?",
    "Feeling afraid as if something awful might happen?": "Feeling afraid as if something awful might happen?",
    "Little interest or pleasure in doing things?": "Little interest or pleasure in doing things?",
    "Feeling down, depressed, or hopeless?": "Feeling down, depressed, or hopeless?",
    "Trouble falling or staying asleep, or sleeping too much?": "Trouble falling or staying asleep, or sleeping too much?",
    "Feeling tired or having little energy?": "Feeling tired or having little energy?",
    "Poor appetite or overeating?": "Poor appetite or overeating?",
    "Feeling bad about yourself - or that you are a failure or have let yourself or your family down?": "Feeling bad about yourself - or that you are a failure or have let yourself or your family down?",
    "Trouble concentrating on things, such as reading the newspaper or watching television?": "Trouble concentrating on things, such as reading the newspaper or watching television?",
    "Moving or speaking so slowly that other people could have noticed? Or the opposite - being so fidgety or restless that you have been moving around a lot more than usual?": "Moving or speaking so slowly that other people could have noticed? Or the opposite - being so fidgety or restless that you have been moving around a lot more than usual?",
    "Thoughts that you would be better off dead, or of hurting yourself in some way?": "Thoughts that you would be better off dead, or of hurting yourself in some way?",`;

const hiKeys = `\n    "Simple Process": "सरल प्रक्रिया",
    "Choose Your Path": "अपना रास्ता चुनें",
    "Start a free session with our clinical AI, or browse our directory of human experts.": "हमारे नैदानिक AI के साथ एक निःशुल्क सत्र शुरू करें, या हमारे मानव विशेषज्ञों की निर्देशिका ब्राउज़ करें।",
    "Begin Healing": "हीलिंग शुरू करें",
    "Use the CBT diary, take psych tests, and track your mood daily to see real progress.": "वास्तविक प्रगति देखने के लिए CBT डायरी का उपयोग करें, मनोवैज्ञानिक परीक्षण लें और दैनिक अपने मूड को ट्रैक करें।",
    "For Professionals": "For Professionals",
    "Join India's Top Network of Mental Health Experts": "Join India's Top Network of Mental Health Experts",
    "Expand your practice, manage appointments seamlessly, and help thousands of users on MindHeal. Our streamlined onboarding takes less than 10 minutes.": "अपना अभ्यास बढ़ाएं, नियुक्तियों को मूल रूप से प्रबंधित करें, और MindHeal पर हजारों उपयोगकर्ताओं की सहायता करें। हमारे सुव्यवस्थित ऑनबोर्डिंग में 10 मिनट से कम समय लगता है।",
    "Sign Up as Counsellor": "Sign Up as Counsellor",
    "Quick Onboarding": "त्वरित ऑनबोर्डिंग",
    "Verify your RCI credentials and set your availability instantly.": "अपने RCI क्रेडेंशियल्स सत्यापित करें और तुरंत अपनी उपलब्धता निर्धारित करें।",
    "Smart Scheduling": "स्मार्ट शेड्यूलिंग",
    "Manage bookings and reminders with our built-in calendar.": "हमारे अंतर्निहित कैलेंडर के साथ बुकिंग और रिमाइंडर्स प्रबंधित करें।",
    "Grow Your Practice": "अपना अभ्यास बढ़ाएं",
    "Get connected with users actively seeking your expertise.": "उन उपयोगकर्ताओं से जुड़ें जो सक्रिय रूप से आपकी विशेषज्ञता की तलाश कर रहे हैं।",
    "Real People. Real Healing.": "सच्चे लोग। सच्ची हीलिंग।",
    "Average App Rating": "Average App Rating",
    "Messages Exchanged": "संदेशों का आदान-प्रदान",
    "Report Reduced Anxiety": "कम हुई चिंता की रिपोर्ट",
    "I struggled with severe anxiety for years. The CBT tools and my therapist on MindHeal completely changed my life.": "मैंने सालों तक गंभीर चिंता से संघर्ष किया। CBT टूल्स और MindHeal पर मेरे थेरेपिस्ट ने मेरा जीवन पूरी तरह से बदल दिया।",
    "The AI companion is incredible for late-night panic attacks. It grounds me instantly.": "देर रात पैनिक अटैक के लिए AI साथी अविश्वसनीय है। यह मुझे तुरंत शांत करता है।",
    "Finally, a platform that understands Indian cultural context. My therapist here gets exactly what I mean without me over-explaining.": "आखिरकार, एक मंच जो भारतीय सांस्कृतिक संदर्भ को समझता है। यहाँ मेरा थेरेपिस्ट बिना अधिक समझाए समझ जाता है कि मेरा क्या मतलब है।",
    "Know Thyself": "स्वयं को जानें",
    "12 Free Clinical Tests.": "12 निःशुल्क क्लिनिकल टेस्ट",
    "Available Assessments": "उपलब्ध आकलन",
    "PHQ-9 (Depression)": "PHQ-9 (Depression)",
    "Patient Health Questionnaire": "Patient Health Questionnaire",
    "Standardized clinical assessment for depression severity.": "अवसाद की गंभीरता के लिए मानकीकृत नैदानिक ​​मूल्यांकन।",
    "GAD-7 (Anxiety)": "GAD-7 (Anxiety)",
    "Generalized Anxiety Disorder Assessment": "Generalized Anxiety Disorder Assessment",
    "Standardized clinical assessment for anxiety severity.": "चिंता की गंभीरता के लिए मानकीकृत नैदानिक ​​मूल्यांकन।",
    "Adult ADHD (ASRS)": "Adult ADHD (ASRS)",
    "Adult ADHD Self-Report Scale": "Adult ADHD Self-Report Scale",
    "Screening tool for Attention Deficit Hyperactivity Disorder.": "ध्यान घाटे की सक्रियता विकार के लिए स्क्रीनिंग टूल।",
    "PTSD Checklist (PCL-5)": "PTSD Checklist (PCL-5)",
    "PTSD Checklist for DSM-5": "PTSD Checklist for DSM-5",
    "Clinical assessment for Post-Traumatic Stress Disorder.": "पोस्ट-ट्रॉमेटिक स्ट्रेस डिसऑर्डर के लिए नैदानिक ​​मूल्यांकन।",
    "Bipolar Spectrum": "बाइपोलर स्पेक्ट्रम",
    "Mood Disorder Questionnaire": "Mood Disorder Questionnaire",
    "Screening tool for bipolar spectrum disorders.": "बाइपोलर स्पेक्ट्रम विकारों के लिए स्क्रीनिंग टूल।",
    "OCD Screening": "OCD स्क्रीनिंग",
    "Obsessive-Compulsive Inventory": "Obsessive-Compulsive Inventory",
    "Assessment for symptoms of Obsessive-Compulsive Disorder.": "ऑब्सेसिव-कंपल्सिव डिसऑर्डर के लक्षणों के लिए मूल्यांकन।",
    "Attachment Style": "अटैचमेंट स्टाइल",
    "Experiences in Close Relationships": "Experiences in Close Relationships",
    "Assessment of adult attachment styles in relationships.": "रिश्तों में वयस्क लगाव शैलियों का मूल्यांकन।",
    "Burnout Inventory": "बर्नआउट इन्वेंटरी",
    "Maslach Burnout Inventory": "Maslach Burnout Inventory",
    "Standardized measure of occupational burnout.": "व्यावसायिक बर्नआउट का मानकीकृत उपाय।",
    "Self-Esteem Index": "आत्म-सम्मान सूचकांक",
    "Rosenberg Self-Esteem Scale": "Rosenberg Self-Esteem Scale",
    "Measure of global self-worth and self-esteem.": "वैश्विक आत्म-मूल्य और आत्म-सम्मान का माप।",
    "Anger Management": "क्रोध प्रबंधन",
    "Buss-Perry Aggression Questionnaire": "Buss-Perry Aggression Questionnaire",
    "Clinical measure of aggressive and angry behavior.": "आक्रामक और गुस्सैल व्यवहार का नैदानिक ​​माप।",
    "Relationship Satisfaction": "रिश्ता संतुष्टि",
    "Couples Satisfaction Index": "Couples Satisfaction Index",
    "Measure of satisfaction in romantic relationships.": "रोमांटिक रिश्तों में संतुष्टि का माप।",
    "Sleep Quality": "नींद की गुणवत्ता",
    "Pittsburgh Sleep Quality Index": "Pittsburgh Sleep Quality Index",
    "Clinical assessment of sleep quality and patterns.": "नींद की गुणवत्ता और पैटर्न का नैदानिक ​​मूल्यांकन।",
    "Question": "प्रश्न",
    "of": "का",
    "Over the last 2 weeks": "पिछले 2 हफ्तों में",
    "Not at all": "बिल्कुल नहीं",
    "Several days": "कई दिन",
    "More than half the days": "आधे से अधिक दिन",
    "Nearly every day": "लगभग हर दिन",
    "Minimal Depression": "न्यूनतम अवсад",
    "Mild Depression": "हल्का अवसाद",
    "Moderate Depression": "मध्यम अवसाद",
    "Moderately Severe Depression": "मध्यम रूप से गंभीर अवसाद",
    "Severe Depression": "गंभीर अवसाद",
    "Minimal Anxiety": "न्यूनतम चिंता",
    "Mild Anxiety": "हल्की चिंता",
    "Moderate Anxiety": "मध्यम चिंता",
    "Severe Anxiety": "गंभीर चिंता",
    "Premium Assessment": "प्रीमियम आकलन",
    "Create a free account to unlock this clinical assessment and track your results.": "इस नैदानिक ​​मूल्यांकन को अनलॉक करने और अपने परिणामों को ट्रैक करने के लिए एक निःशुल्क खाता बनाएं।",
    "Unlock Assessment": "आकलन अनलॉक करें",
    "Assessment Complete": "मूल्यांकन पूर्ण",
    "This is a screening tool, not a diagnosis. To discuss these results, please consult a clinical psychologist.": "यह एक screening tool है, निदान नहीं। इन परिणामों पर चर्चा करने के लिए, कृपया एक clinical psychologist से परामर्श लें।",
    "Discuss with a Counsellor": "Counsellor से चर्चा करें",
    "Retake Assessment": "पुनः परीक्षण लें",
    "The Top 1%": "शीर्ष 1%",
    "Meet Your Match.": "अपने आदर्श साथी से मिलें।",
    "All Experts": "All Experts",
    "Clinical Psychologists": "Clinical Psychologists",
    "Trauma Specialists": "Trauma Specialists",
    "Relationship Counsellors": "Relationship Counsellors",
    "Child Psychologists": "Child Psychologists",
    "Book": "बुक करें",
    "12+ Years Exp": "12+ Years Exp",
    "8+ Years Exp": "8+ Years Exp",
    "5+ Years Exp": "5+ Years Exp",
    "15+ Years Exp": "15+ Years Exp",
    "CLINICAL PSYCHOLOGIST": "CLINICAL PSYCHOLOGIST",
    "RELATIONSHIP COUNSELLOR": "RELATIONSHIP COUNSELLOR",
    "TRAUMA SPECIALIST": "TRAUMA SPECIALIST",
    "CHILD PSYCHOLOGIST": "CHILD PSYCHOLOGIST",
    "Sign up instantly. Your data is encrypted and completely confidential.": "तुरंत साइन अप करें। आपका डेटा एन्क्रिप्टेड और पूरी तरह से गोपनीय है।",
    "Feeling nervous, anxious, or on edge?": "घबराहट, चिंता या बेचैनी महसूस होना?",
    "Not being able to stop or control worrying?": "चिंता करना बंद या नियंत्रित न कर पाना?",
    "Worrying too much about different things?": "अलग-अलग चीजों के बारे में बहुत अधिक चिंता करना?",
    "Trouble relaxing?": "आराम करने में परेशानी?",
    "Being so restless that it is hard to sit still?": "इतने बेचैन होना कि चुपचाप बैठना मुश्किल हो?",
    "Becoming easily annoyed or irritable?": "आसानी से चिढ़ जाना या चिड़चिड़ा होना?",
    "Feeling afraid as if something awful might happen?": "डर लगना जैसे कि कुछ भयानक होने वाला हो?",
    "Little interest or pleasure in doing things?": "कामों को करने में बहुत कम रुचि या आनंद होना?",
    "Feeling down, depressed, or hopeless?": "उदास, निराश या लाचार महसूस होना?",
    "Trouble falling or staying asleep, or sleeping too much?": "नींद आने या सोते रहने में परेशानी, या बहुत अधिक सोना?",
    "Feeling tired or having little energy?": "थका हुआ महसूस होना या ऊर्जा की कमी होना?",
    "Poor appetite or overeating?": "कम भूख लगना या बहुत अधिक खाना?",
    "Feeling bad about yourself - or that you are a failure or have let yourself or your family down?": "अपने बारे में बुरा महसूस करना - या यह कि आप असफल हैं या आपने खुद को या अपने परिवार को निराश किया है?",
    "Trouble concentrating on things, such as reading the newspaper or watching television?": "चीजों पर ध्यान केंद्रित करने में परेशानी, जैसे समाचार पत्र पढ़ना या टेलीविजन देखना?",
    "Moving or speaking so slowly that other people could have noticed? Or the opposite - being so fidgety or restless that you have been moving around a lot more than usual?": "इतनी धीमी गति से चलना या बोलना कि अन्य लोग ध्यान दे सकें? या इसके विपरीत - इतना बेचैन या अशांत होना कि आप सामान्य से बहुत अधिक घूम रहे हों?",
    "Thoughts that you would be better off dead, or of hurting yourself in some way?": "यह विचार आना कि मर जाना बेहतर होगा, या किसी तरह खुद को नुकसान पहुँचाना?",`;

const taKeys = `\n    "Simple Process": "எளிய செயல்முறை",
    "Choose Your Path": "உங்கள் பாதையைத் தேர்ந்தெடுக்கவும்",
    "Start a free session with our clinical AI, or browse our directory of human experts.": "எங்கள் மருத்துவ AI உடன் இலவச அமர்வைத் தொடங்கவும் அல்லது மனித நிபுணர்களின் கோப்பகத்தை உலாவவும்.",
    "Begin Healing": "குணமடையத் தொடங்குங்கள்",
    "Use the CBT diary, take psych tests, and track your mood daily to see real progress.": "உண்மையான முன்னேற்றத்தைக் காண CBT டைரியைப் பயன்படுத்தவும், உளவியல் சோதனைகளை மேற்கொள்ளவும் மற்றும் தினசரி உங்கள் மனநிலையைக் கண்காணிக்கும்.",
    "For Professionals": "For Professionals",
    "Join India's Top Network of Mental Health Experts": "Join India's Top Network of Mental Health Experts",
    "Expand your practice, manage appointments seamlessly, and help thousands of users on MindHeal. Our streamlined onboarding takes less than 10 minutes.": "உங்கள் பயிற்சியை விரிவாக்குங்கள், சந்திப்புகளை தடையின்றி நிர்வகியுங்கள் மற்றும் MindHeal இல் ஆயிரக்கணக்கான பயனர்களுக்கு உதவுங்கள். எங்களின் எளிமையான ஆன்போர்டிங் 10 நிமிடங்களுக்கும் குறைவாகவே ஆகும்.",
    "Sign Up as Counsellor": "Sign Up as Counsellor",
    "Quick Onboarding": "விரைவான ஆன்போர்டிங்",
    "Verify your RCI credentials and set your availability instantly.": "உங்கள் RCI சான்றுகளைச் சரிபார்த்து, உங்கள் கிடைக்கும் தன்மையை உடனடியாக அமைக்கவும்.",
    "Smart Scheduling": "ஸ்மார்ட் திட்டமிடல்",
    "Manage bookings and reminders with our built-in calendar.": "எங்களின் உள்ளமைக்கப்பட்ட காலெண்டரைக் கொண்டு முன்பதிவுகள் மற்றும் நினைவூட்டல்களை நிர்வகிக்கவும்.",
    "Grow Your Practice": "உங்கள் பயிற்சியை வளர்த்துக் கொள்ளுங்கள்",
    "Get connected with users actively seeking your expertise.": "உங்கள் நிபுணத்துவத்தை தீவிரமாகத் தேடும் பயனர்களுடன் இணையுங்கள்.",
    "Real People. Real Healing.": "உண்மையான மனிதர்கள். உண்மையான குணப்படுத்துதல்.",
    "Average App Rating": "Average App Rating",
    "Messages Exchanged": "பரிமாறப்பட்ட செய்திகள்",
    "Report Reduced Anxiety": "குறைக்கப்பட்ட பதட்டத்தை புகாரளிக்கவும்",
    "I struggled with severe anxiety for years. The CBT tools and my therapist on MindHeal completely changed my life.": "நான் பல ஆண்டுகளாக கடுமையான பதட்டத்துடன் போராடினேன். CBT கருவிகள் மற்றும் MindHeal இல் உள்ள எனது சிகிச்சையாளர் எனது வாழ்க்கையை முற்றிலும் மாற்றினர்.",
    "The AI companion is incredible for late-night panic attacks. It grounds me instantly.": "இரவு நேர பீதி தாக்குதல்களுக்கு AI துணை நம்பமுடியாதது. இது என்னை உடனடியாக அமைதிப்படுத்துகிறது.",
    "Finally, a platform that understands Indian cultural context. My therapist here gets exactly what I mean without me over-explaining.": "இறுதியாக, இந்திய கலாச்சார சூழலை புரிந்து கொள்ளும் ஒரு தளம். நான் அதிகமாக விளக்கமளிக்காமலேயே எனது சிகிச்சையாளர் நான் சொல்வதை சரியாக புரிந்துகொள்கிறார்.",
    "Know Thyself": "உன்னை அறிந்துகொள்",
    "12 Free Clinical Tests.": "12 இலவச மருத்துவ சோதனைகள்",
    "Available Assessments": "கிடைக்கக்கூடிய மதிப்பீடுகள்",
    "PHQ-9 (Depression)": "PHQ-9 (Depression)",
    "Patient Health Questionnaire": "Patient Health Questionnaire",
    "Standardized clinical assessment for depression severity.": "மனச்சோர்வின் தீவிரத்திற்கான தரப்படுத்தப்பட்ட மருத்துவ மதிப்பீடு.",
    "GAD-7 (Anxiety)": "GAD-7 (Anxiety)",
    "Generalized Anxiety Disorder Assessment": "Generalized Anxiety Disorder Assessment",
    "Standardized clinical assessment for anxiety severity.": "பதட்டத்தின் தீவிரத்திற்கான தரப்படுத்தப்பட்ட மருத்துவ மதிப்பீடு.",
    "Adult ADHD (ASRS)": "Adult ADHD (ASRS)",
    "Adult ADHD Self-Report Scale": "Adult ADHD Self-Report Scale",
    "Screening tool for Attention Deficit Hyperactivity Disorder.": "கவனம் பற்றாக்குறை அதிவேகத்தன்மை கோளாறுக்கான திரையிடல் கருவி.",
    "PTSD Checklist (PCL-5)": "PTSD Checklist (PCL-5)",
    "PTSD Checklist for DSM-5": "PTSD Checklist for DSM-5",
    "Clinical assessment for Post-Traumatic Stress Disorder.": "ஆதிர்ச்சிக்குப் பிந்தைய மன அழுத்தக் கோளாறுக்கான மருத்துவ மதிப்பீடு.",
    "Bipolar Spectrum": "இருமுனை நிறமாலை",
    "Mood Disorder Questionnaire": "Mood Disorder Questionnaire",
    "Screening tool for bipolar spectrum disorders.": "இருமுனை நிறமாலை கோளாறுகளுக்கான திரையிடல் கருவி.",
    "OCD Screening": "OCD திரையிடல்",
    "Obsessive-Compulsive Inventory": "Obsessive-Compulsive Inventory",
    "Assessment for symptoms of Obsessive-Compulsive Disorder.": "அப்செசிவ்-கம்பல்சிவ் கோளாறின் அறிகுறிகளுக்கான மதிப்பீடு.",
    "Attachment Style": "இணைப்பு பாணி",
    "Experiences in Close Relationships": "Experiences in Close Relationships",
    "Assessment of adult attachment styles in relationships.": "உறவுகளில் பெரியோர்களின் இணைப்பு பாணிகளின் மதிப்பீடு.",
    "Burnout Inventory": "பர்ன்அவுட் சரக்கு",
    "Maslach Burnout Inventory": "Maslach Burnout Inventory",
    "Standardized measure of occupational burnout.": "தொழில்சார் பர்ன்அவுட்டின் தரப்படுத்தப்பட்ட அளவு.",
    "Self-Esteem Index": "சுயமரியாதை குறியீடு",
    "Rosenberg Self-Esteem Scale": "Rosenberg Self-Esteem Scale",
    "Measure of global self-worth and self-esteem.": "உலகளாவிய சுயமதிப்பு மற்றும் சுயமரியாதையின் அளவு.",
    "Anger Management": "கோப மேலாண்மை",
    "Buss-Perry Aggression Questionnaire": "Buss-Perry Aggression Questionnaire",
    "Clinical measure of aggressive and angry behavior.": "ஆக்கிரமிப்பு மற்றும் கோபமான நடத்தையின் மருத்துவ அளவு.",
    "Relationship Satisfaction": "உறவு திருப்தி",
    "Couples Satisfaction Index": "Couples Satisfaction Index",
    "Measure of satisfaction in romantic relationships.": "காதல் உறவுகளில் திருப்தியின் அளவு.",
    "Sleep Quality": "தூக்கத்தின் தரம்",
    "Pittsburgh Sleep Quality Index": "Pittsburgh Sleep Quality Index",
    "Clinical assessment of sleep quality and patterns.": "தூக்கத்தின் தரம் மற்றும் வடிவங்களின் மருத்துவ மதிப்பீடு.",
    "Question": "கேள்வி",
    "of": "இல்",
    "Over the last 2 weeks": "கடந்த 2 வாரங்களில்",
    "Not at all": "இல்லவே இல்லை",
    "Several days": "பல நாட்கள்",
    "More than half the days": "பாதிக்கும் மேற்பட்ட நாட்கள்",
    "Nearly every day": "கிட்டத்தட்ட ஒவ்வொரு நாளும்",
    "Minimal Depression": "குறைந்தபட்ச மனச்சோர்வு",
    "Mild Depression": "லேசான மனச்சோர்வு",
    "Moderate Depression": "மிதமான மனச்சோர்வு",
    "Moderately Severe Depression": "மிதமான கடுமையான மனச்சோர்வு",
    "Severe Depression": "கடுமையான மனச்சோர்வு",
    "Minimal Anxiety": "குறைந்தபட்ச பதட்டம்",
    "Mild Anxiety": "லேசான பதட்டம்",
    "Moderate Anxiety": "மிதமான பதட்டம்",
    "Severe Anxiety": "கடுமையான பதட்டம்",
    "Premium Assessment": "பிரீமியம் மதிப்பீடு",
    "Create a free account to unlock this clinical assessment and track your results.": "இந்த மருத்துவ மதிப்பீட்டைத் திறக்கவும் உங்கள் முடிவுகளைக் கண்காணிக்கவும் இலவசக் கணக்கை உருவாக்கவும்.",
    "Unlock Assessment": "மதிப்பீட்டைத் திறக்கவும்",
    "Assessment Complete": "மதிப்பீடு முடிந்தது",
    "This is a screening tool, not a diagnosis. To discuss these results, please consult a clinical psychologist.": "இது ஒரு திரையிடல் கருவி மட்டுமே, நோய் கண்டறிதல் அல்ல. இந்த முடிவுகளைப் பற்றி விவாதிக்க, தயவுசெய்து ஒரு clinical psychologist-ஐ அணுகவும்.",
    "Discuss with a Counsellor": "Counsellor உடன் விவாதிக்கவும்",
    "Retake Assessment": "மீண்டும் மதிப்பீட்டை மேற்கொள்ளவும்",
    "The Top 1%": "சிறந்த 1%",
    "Meet Your Match.": "உங்கள் பொருத்தத்தைக் கண்டறியவும்.",
    "All Experts": "All Experts",
    "Clinical Psychologists": "Clinical Psychologists",
    "Trauma Specialists": "Trauma Specialists",
    "Relationship Counsellors": "Relationship Counsellors",
    "Child Psychologists": "Child Psychologists",
    "Book": "பதிவு செய்யவும்",
    "12+ Years Exp": "12+ Years Exp",
    "8+ Years Exp": "8+ Years Exp",
    "5+ Years Exp": "5+ Years Exp",
    "15+ Years Exp": "15+ Years Exp",
    "CLINICAL PSYCHOLOGIST": "CLINICAL PSYCHOLOGIST",
    "RELATIONSHIP COUNSELLOR": "RELATIONSHIP COUNSELLOR",
    "TRAUMA SPECIALIST": "TRAUMA SPECIALIST",
    "CHILD PSYCHOLOGIST": "CHILD PSYCHOLOGIST",
    "Sign up instantly. Your data is encrypted and completely confidential.": "உடனடியாக பதிவு செய்யவும். உங்கள் தரவு குறியாக்கம் செய்யப்பட்டு முற்றிலும் ரகசியமாக வைக்கப்படும்.",
    "Feeling nervous, anxious, or on edge?": "பதட்டமாக, கவலையாக அல்லது விளிம்பில் இருப்பது போல் உணர்கிறீர்களா?",
    "Not being able to stop or control worrying?": "கவலைப்படுவதை நிறுத்தவோ அல்லது கட்டுப்படுத்தவோ முடியவில்லையா?",
    "Worrying too much about different things?": "பல்வேறு விஷயங்களைப் பற்றி அதிகமாக கவலைப்படுகிறீர்களா?",
    "Trouble relaxing?": "ஓய்வெடுப்பதில் சிரமமா?",
    "Being so restless that it is hard to sit still?": "ஒரே இடத்தில் அமைதியாக அமர முடியாத அளவுக்கு அமைதியின்மையாக இருக்கிறீர்களா?",
    "Becoming easily annoyed or irritable?": "எளிதில் எரிச்சலடைவது அல்லது கோபமடைவது?",
    "Feeling afraid as if something awful might happen?": "ஏதாவது மோசமான ஒன்று நடந்துவிடுமோ என்று பயமாக இருக்கிறதா?",
    "Little interest or pleasure in doing things?": "விஷયங்களைச் செய்வதில் ஆர்வம் அல்லது மகிழ்ச்சி குறைவாக இருக்கிறதா?",
    "Feeling down, depressed, or hopeless?": "மனம் சோர்ந்து, மனச்சோர்வடைந்து அல்லது நம்பிக்கையற்றவராக உணர்கிறீர்களா?",
    "Trouble falling or staying asleep, or sleeping too much?": "தூங்குவதில் அல்லது தூக்கத்தைத் தொடர்வதில் சிரமம், அல்லது அதிக தூக்கம்?",
    "Feeling tired or having little energy?": "சோர்வாக அல்லது குறைந்த ஆற்றல் கொண்டதாக உணர்கிறீர்களா?",
    "Poor appetite or overeating?": "குறைந்த பசி அல்லது அதிகமாக சாப்பிடுவது?",
    "Feeling bad about yourself - or that you are a failure or have let yourself or your family down?": "உங்களைப் பற்றி மோசமாக உணர்கிறீர்களா - அல்லது நீங்கள் ஒரு தோல்வி அல்லது உங்களுக்கோ அல்லது உங்கள் குடும்பத்தினருக்கோ ஏமாற்றத்தை ஏற்படுத்திவிட்டதாக உணர்கிறீர்களா?",
    "Trouble concentrating on things, such as reading the newspaper or watching television?": "செய்தித் தாள் வாசிப்பது அல்லது தொலைக்காட்சி பார்ப்பது போன்ற விஷயங்களில் கவனம் செலுத்துவதில் சிரமமா?",
    "Moving or speaking so slowly that other people could have noticed? Or the opposite - being so fidgety or restless that you have been moving around a lot more than usual?": "மற்றவர்கள் கவனிக்கும் அளவுக்கு மிகவும் மெதுவாக நகர்வது அல்லது பேசுவது? அல்லது அதற்கு நேர்மாறாக - வழக்கத்தை விட அதிகமாக அங்கும் இங்கும் நகரும் அளவுக்கு அமைதியற்றவராக இருப்பது?",
    "Thoughts that you would be better off dead, or of hurting yourself in some way?": "இறந்துவிடுவது நல்லது என்ற எண்ணம் அல்லது ஏதோ ஒரு வகையில் உங்களுக்கு நீங்களே தீங்கு விளைவித்துக் கொள்ளும் எண்ணம் ஏற்படுகிறதா?",`;

const teKeys = `\n    "Simple Process": "సాధారణ ప్రక్రియ",
    "Choose Your Path": "మీ మార్గాన్ని ఎంచుకోండి",
    "Start a free session with our clinical AI, or browse our directory of human experts.": "మా క్లినికల్ AIతో ఉచిత సెషన్‌ను ప్రారంభించండి లేదా మా మానవ నిపుణుల డైరెక్టరీని బ్రౌజ్ చేయండి.",
    "Begin Healing": "నయం చేయడం ప్రారంభించండి",
    "Use the CBT diary, take psych tests, and track your mood daily to see real progress.": "నిజమైన పురోగతిని చూడటానికి CBT డైరీని ఉపయోగించండి, మానసిక పరీక్షలను తీసుకోండి మరియు ప్రతిరోజూ మీ మూడ్‌ని ట్రాక్ చేయండి.",
    "For Professionals": "For Professionals",
    "Join India's Top Network of Mental Health Experts": "Join India's Top Network of Mental Health Experts",
    "Expand your practice, manage appointments seamlessly, and help thousands of users on MindHeal. Our streamlined onboarding takes less than 10 minutes.": "మీ ప్రాక్టీస్‌ను విస్తరించుకోండి, అపాయింట్‌మెంట్‌లను సజావుగా నిర్వహించండి మరియు MindHealలో వేలాది మంది వినియోగదారులకు సహాయం చేయండి. మా సులభతరమైన ఆన్‌బోర్డింగ్ 10 నిమిషాల కంటే తక్కువ సమయం పడుతుంది.",
    "Sign Up as Counsellor": "Sign Up as Counsellor",
    "Quick Onboarding": "త్వరిత ఆన్‌బోర్డింగ్",
    "Verify your RCI credentials and set your availability instantly.": "మీ RCI ఆధారాలను ధృవీకరించండి మరియు మీ లభ్యతను తక్షణమే సెట్ చేయండి.",
    "Smart Scheduling": "స్మార్ట్ షెడ్యూలింగ్",
    "Manage bookings and reminders with our built-in calendar.": "మా అంతర్నిర్మిత క్యాలెండర్‌తో బుకింగ్‌లు మరియు రిమైండర్‌లను నిర్వహించండి.",
    "Grow Your Practice": "మీ ప్రాక్టీస్‌ను పెంచుకోండి",
    "Get connected with users actively seeking your expertise.": "మీ నైపుణ్యం కోసం చురుకుగా వెతుకుతున్న వినియోగదారులతో కనెక్ట్ అవ్వండి.",
    "Real People. Real Healing.": "నిజమైన వ్యక్తులు. నిజమైన స్వస్థత.",
    "Average App Rating": "Average App Rating",
    "Messages Exchanged": "సందేశాల మార్పిడి",
    "Report Reduced Anxiety": "తగ్గిన ఆందోళన నివేదిక",
    "I struggled with severe anxiety for years. The CBT tools and my therapist on MindHeal completely changed my life.": "నేను చాలా సంవత్సరాలుగా తీవ్రమైన ఆందోళనతో పోరాడాను. CBT సాధనాలు మరియు MindHeal లో నా థెరపిస్ట్ నా జీవితాన్ని పూర్తిగా మార్చేశారు.",
    "The AI companion is incredible for late-night panic attacks. It grounds me instantly.": "అర్ధరాత్రి పానిక్ అటాక్స్ కోసం AI కంపానియన్ అద్భుతమైనది. ఇది నన్ను తక్షణమే ప్రశాంతపరుస్తుంది.",
    "Finally, a platform that understands Indian cultural context. My therapist here gets exactly what I mean without me over-explaining.": "చివరగా, భారతీయ సాంస్కృతిక సందర్భాన్ని అర్థం చేసుకునే వేదిక. నేను ఎక్కువగా వివరించకుండానే ఇక్కడి నా థెరపిస్ట్‌కు నేను చెప్పదలచుకున్నది సరిగ్గా అర్థమవుతుంది.",
    "Know Thyself": "నిన్ను నీవు తెలుసుకో",
    "12 Free Clinical Tests.": "12 ఉచిత క్లినికల్ పరీక్షలు",
    "Available Assessments": "అందుబాటులో ఉన్న అంచనాలు",
    "PHQ-9 (Depression)": "PHQ-9 (Depression)",
    "Patient Health Questionnaire": "Patient Health Questionnaire",
    "Standardized clinical assessment for depression severity.": "డిప్రెషన్ తీవ్రత కోసం ప్రామాణిక క్లినికల్ అసెస్‌మెంట్.",
    "GAD-7 (Anxiety)": "GAD-7 (Anxiety)",
    "Generalized Anxiety Disorder Assessment": "Generalized Anxiety Disorder Assessment",
    "Standardized clinical assessment for anxiety severity.": "ఆందోళన తీవ్రత కోసం ప్రామాణిక క్లినికల్ అసెస్‌మెంట్.",
    "Adult ADHD (ASRS)": "Adult ADHD (ASRS)",
    "Adult ADHD Self-Report Scale": "Adult ADHD Self-Report Scale",
    "Screening tool for Attention Deficit Hyperactivity Disorder.": "అటెన్షన్ డెఫిసిట్ హైపర్యాక్టివిటీ డిజార్డర్ కోసం స్క్రీనింగ్ సాధనం.",
    "PTSD Checklist (PCL-5)": "PTSD Checklist (PCL-5)",
    "PTSD Checklist for DSM-5": "PTSD Checklist for DSM-5",
    "Clinical assessment for Post-Traumatic Stress Disorder.": "పోస్ట్-ట్రామాటిక్ స్ట్రెస్ డిజార్డర్ కోసం క్ліనికల్ అసెస్‌మెంట్.",
    "Bipolar Spectrum": "బైపోలార్ స్పెక్ట్రమ్",
    "Mood Disorder Questionnaire": "Mood Disorder Questionnaire",
    "Screening tool for bipolar spectrum disorders.": "బైపోలార్ స్పెక్ట్రమ్ రుగ్మతల కోసం స్క్రీనింగ్ సాధనం.",
    "OCD Screening": "OCD స్క్రీనింగ్",
    "Obsessive-Compulsive Inventory": "Obsessive-Compulsive Inventory",
    "Assessment for symptoms of Obsessive-Compulsive Disorder.": "అబ్సెసివ్-కంపల్సివ్ డిజార్డర్ లక్షణాల కోసం అసెస్‌మెంట్.",
    "Attachment Style": "అటాచ్మెంట్ శైలి",
    "Experiences in Close Relationships": "Experiences in Close Relationships",
    "Assessment of adult attachment styles in relationships.": "సంబంధాలలో వయోజన అటాచ్మెంట్ శైలుల అంచనా.",
    "Burnout Inventory": "బర్నౌట్ ఇన్వెంటరీ",
    "Maslach Burnout Inventory": "Maslach Burnout Inventory",
    "Standardized measure of occupational burnout.": "వృత్తిపరమైన బర్నౌట్ యొక్క ప్రామాణిక కొలత.",
    "Self-Esteem Index": "ఆత్మగౌరవ సూచిక",
    "Rosenberg Self-Esteem Scale": "Rosenberg Self-Esteem Scale",
    "Measure of global self-worth and self-esteem.": "గ్లోబల్ సెల్ఫ్-వర్త్ మరియు ఆత్మగౌరవం యొక్క కొలత.",
    "Anger Management": "కోప నిర్వహణ",
    "Buss-Perry Aggression Questionnaire": "Buss-Perry Aggression Questionnaire",
    "Clinical measure of aggressive and angry behavior.": "ఆక్రమణ మరియు కోపంతో కూడిన ప్రవర్తన యొక్క క్లినికల్ కొలత.",
    "Relationship Satisfaction": "సంబంధాల సంతృప్తి",
    "Couples Satisfaction Index": "Couples Satisfaction Index",
    "Measure of satisfaction in romantic relationships.": "శృంగార సంబంధాలలో సంతృప్తి కొలత.",
    "Sleep Quality": "నిద్ర నాణ్యత",
    "Pittsburgh Sleep Quality Index": "Pittsburgh Sleep Quality Index",
    "Clinical assessment of sleep quality and patterns.": "నిద్ర నాణ్యత మరియు నమూనాల క్లినికల్ అసెస్‌మెంట్.",
    "Question": "ప్రశ్న",
    "of": "లో",
    "Over the last 2 weeks": "గత 2 వారాలుగా",
    "Not at all": "అస్సలు లేదు",
    "Several days": "కొన్ని రోజులు",
    "More than half the days": "సగానికి పైగా రోజులు",
    "Nearly every day": "దాదాపు ప్రతి రోజు",
    "Minimal Depression": "కనిష్ట డిప్రెషన్",
    "Mild Depression": "తేలికపాటి డిప్రెషన్",
    "Moderate Depression": "మధ్యస్థ డిప్రెషన్",
    "Moderately Severe Depression": "మధ్యస్థ తీవ్రమైన డిప్రెషన్",
    "Severe Depression": "తీవ్రమైన డిప్రెషన్",
    "Minimal Anxiety": "కనిష్ట ఆందోళన",
    "Mild Anxiety": "తేలికపాటి ఆందోళన",
    "Moderate Anxiety": "మధ్యస్థ ఆందోళన",
    "Severe Anxiety": "తీవ్రమైన ఆందోళన",
    "Premium Assessment": "ప్రీమియం అసెస్‌మెంట్",
    "Create a free account to unlock this clinical assessment and track your results.": "ఈ క్లినికల్ అసెస్‌మెంట్‌ను అన్‌లాక్ చేయడానికి మరియు మీ ఫలితాలను track చేయడానికి ఉచిత ఖాతాను సృష్టించండి.",
    "Unlock Assessment": "అసెస్‌మెంట్‌ను అన్‌లాక్ చేయండి",
    "Assessment Complete": "అసెస్‌మెంట్ పూర్తయింది",
    "This is a screening tool, not a diagnosis. To discuss these results, please consult a clinical psychologist.": "ఇది స్క్రీనింగ్ సాధనం మాత్రమే, నిర్ధారణ కాదు. ఈ ఫలితాలను చర్చించడానికి, దయచేసి clinical psychologistని సంప్రదించండి.",
    "Discuss with a Counsellor": "Counsellor తో చర్చించండి",
    "Retake Assessment": "మళ్లీ అసెస్‌మెంట్ తీసుకోండి",
    "The Top 1%": "టాప్ 1%",
    "Meet Your Match.": "మీకు సరిపోయే వారిని కనుగొనండి.",
    "All Experts": "All Experts",
    "Clinical Psychologists": "Clinical Psychologists",
    "Trauma Specialists": "Trauma Specialists",
    "Relationship Counsellors": "Relationship Counsellors",
    "Child Psychologists": "Child Psychologists",
    "Book": "బుక్ చేయండి",
    "12+ Years Exp": "12+ Years Exp",
    "8+ Years Exp": "8+ Years Exp",
    "5+ Years Exp": "5+ Years Exp",
    "15+ Years Exp": "15+ Years Exp",
    "CLINICAL PSYCHOLOGIST": "CLINICAL PSYCHOLOGIST",
    "RELATIONSHIP COUNSELLOR": "RELATIONSHIP COUNSELLOR",
    "TRAUMA SPECIALIST": "TRAUMA SPECIALIST",
    "CHILD PSYCHOLOGIST": "CHILD PSYCHOLOGIST",
    "Sign up instantly. Your data is encrypted and completely confidential.": "తక్షణమే సైన్ అప్ చేయండి. మీ డేటా ఎన్‌క్రిప్ట్ చేయబడింది మరియు పూర్తిగా గోప్యంగా ఉంటుంది.",
    "Feeling nervous, anxious, or on edge?": "కంగారుగా, ఆందోళనగా లేదా అసహనంగా అనిపిస్తోందా?",
    "Not being able to stop or control worrying?": "ఆందోళన పడటాన్ని ఆపలేకపోతున్నారా లేదా నియంత్రించలేకపోతున్నారా?",
    "Worrying too much about different things?": "విభిన్న విషయాల గురించి ఎక్కువగా ఆందోళన చెందుతున్నారా?",
    "Trouble relaxing?": "ప్రశాంతంగా ఉండటంలో ఇబ్బందిగా ఉందా?",
    "Being so restless that it is hard to sit still?": "నిశ్చలంగా కూర్చోలేనంత అశాంతిగా ఉన్నారా?",
    "Becoming easily annoyed or irritable?": "త్వరగా విసుగు చెందడం లేదా కోపగించుకోవడం జరుగుతుందా?",
    "Feeling afraid as if something awful might happen?": "ఏదో ఘోరం జరిగిపోతుందన్నట్లు భయంగా అనిపిస్తోందా?",
    "Little interest or pleasure in doing things?": "పనులను చేయడంలో చాలా తక్కువ ఆసక్తి లేదా ఆనందం ఉందా?",
    "Feeling down, depressed, or hopeless?": "నిరుత్సాహంగా, కుంగిపోయినట్లు లేదా నిరాశగా అనిపిస్తోందా?",
    "Trouble falling or staying asleep, or sleeping too much?": "నిద్రపోవడంలో లేదా నిద్ర కొనసాగించడంలో ఇబ్బందిగా ఉందా, లేదా అతిగా నిద్రపోతున్నారా?",
    "Feeling tired or having little energy?": "అలసిపోయినట్లు లేదా తక్కువ శక్తి ఉన్నట్లు అనిపిస్తోందా?",
    "Poor appetite or overeating?": "ఆకలి లేకపోవడం లేదా అతిగా తినడం జరుగుతుందా?",
    "Feeling bad about yourself - or that you are a failure or have let yourself or your family down?": "మీ గురించి మీకు చెడుగా అనిపిస్తోందా - లేదా మీరు విఫలమయ్యారని లేదా మిమ్మల్ని లేదా మీ కుటుంబాన్ని నిరాశపరిచారని అనిపిస్తోందా?",
    "Trouble concentrating on things, such as reading the newspaper or watching television?": "వార్తాపత్రిక చదవడం లేదా టెలివిజన్ చూడటం వంటి విషయాలపై దృష్టి పెట్టడంలో ఇబ్బందిగా ఉందా?",
    "Moving or speaking so slowly that other people could have noticed? Or the opposite - being so fidgety or restless that you have been moving around a lot more than usual?": "ఇతరులు గమనించేంత నెమ్మదిగా కదలడం లేదా మాట్లాడటం జరుగుతుందా? లేదా దానికి విరుద్ధంగా - సాధారణం కంటే చాలా ఎక్కువగా తిరిగేంత అశాంతిగా ఉన్నారా?",
    "Thoughts that you would be better off dead, or of hurting yourself in some way?": "చనిపోతే బాగుండునని, లేదా ఏదో రకంగా మిమ్మల్ని మీరు గాయపరుచుకోవాలనే ఆలోచనలు వస్తున్నాయా?",`;

const guKeys = `\n    "Simple Process": "સરળ પ્રક્રિયા",
    "Choose Your Path": "તમારો રસ્તો પસંદ કરો",
    "Start a free session with our clinical AI, or browse our directory of human experts.": "અમારી ક્લિનિકલ AI સાથે મફત સત્ર શરૂ કરો, અથવા માનવ નિષ્ણાતોની અમારી ડિરેક્ટરી બ્રાઉઝ કરો.",
    "Begin Healing": "હીલિંગ શરૂ કરો",
    "Use the CBT diary, take psych tests, and track your mood daily to see real progress.": "વાસ્તવિક પ્રગતિ જોવા માટે CBT ડાયરીનો ઉપયોગ કરો, મનોવૈજ્ઞાનિક પરીક્ષણો લો અને દરરોજ તમારા મૂડને ટ્રૅક કરો.",
    "For Professionals": "For Professionals",
    "Join India's Top Network of Mental Health Experts": "Join India's Top Network of Mental Health Experts",
    "Expand your practice, manage appointments seamlessly, and help thousands of users on MindHeal. Our streamlined onboarding takes less than 10 minutes.": "તમારી પ્રેક્ટિસનો વિસ્તાર કરો, એપોઇન્ટમેન્ટ્સ એકીકૃત રીતે મેનેજ કરો અને MindHeal પર હજારો વપરાશકર્તાઓને મદદ કરો. અમારું સુવ્યવસ્થિત ઓનબોર્ડિંગ 10 મિનિટથી ઓછો સમય લે છે.",
    "Sign Up as Counsellor": "Sign Up as Counsellor",
    "Quick Onboarding": "ઝડપી ઓનબોર્ડિંગ",
    "Verify your RCI credentials and set your availability instantly.": "તમારા RCI ઓળખપત્રો ચકાસો અને તમારી ઉપલબ્ધતા તરત જ સેટ કરો.",
    "Smart Scheduling": "સ્માર્ટ શેડ્યુલિંગ",
    "Manage bookings and reminders with our built-in calendar.": "અમારા બિલ્ટ-ઇન કેલેન્ડર સાથે બુકિંગ અને રીમાઇન્ડર્સ મેનેજ કરો.",
    "Grow Your Practice": "તમારી પ્રેક્ટિસ વધારો",
    "Get connected with users actively seeking your expertise.": "તમારી કુશળતા સક્રિયપણે શોધતા વપરાશકર્તાઓ સાથે જોડાઓ.",
    "Real People. Real Healing.": "વાસ્તવિક લોકો. વાસ્તવિક હીલિંગ.",
    "Average App Rating": "Average App Rating",
    "Messages Exchanged": "સંદેશાઓની આપ-લે",
    "Report Reduced Anxiety": "ચિંતામાં ઘટાડો થયો હોવાનો અહેવાલ",
    "I struggled with severe anxiety for years. The CBT tools and my therapist on MindHeal completely changed my life.": "મેં વર્ષો સુધી ગંભીર ચિંતા સાથે સંઘર્ષ કર્યો. CBT સાધનો અને MindHeal પરના મારા થેરાપિસ્ટે મારું જીવન સંપૂર્ણપણે બદલી નાખ્યું.",
    "The AI companion is incredible for late-night panic attacks. It grounds me instantly.": "મોડી રાતના ગભરાટના હુમલા માટે AI સાથી અદ્ભુત છે. તે મને તરત જ શાંત કરે છે.",
    "Finally, a platform that understands Indian cultural context. My therapist here gets exactly what I mean without me over-explaining.": "છેવટે, એક પ્લેટફોર્મ જે ભારતીય સાંસ્કૃતિક સંદર્ભને સમજે છે. અહીં મારા થેરાપિસ્ટ હું અતિશય સમજાવ્યા વિના બરાબર સમજી જાય છે કે મારો કહેવાનો અર્થ શું છે.",
    "Know Thyself": "તમારી જાતને જાણો",
    "12 Free Clinical Tests.": "12 મફત ક્લિનિકલ ટેસ્ટ",
    "Available Assessments": "ઉપલબ્ધ મૂલ્યાંકન",
    "PHQ-9 (Depression)": "PHQ-9 (Depression)",
    "Patient Health Questionnaire": "Patient Health Questionnaire",
    "Standardized clinical assessment for depression severity.": "ડિપ્રેશનની ગંભીરતા માટે પ્રમાણિત ક્લિનિકલ મૂલ્યાંકન.",
    "GAD-7 (Anxiety)": "GAD-7 (Anxiety)",
    "Generalized Anxiety Disorder Assessment": "Generalized Anxiety Disorder Assessment",
    "Standardized clinical assessment for anxiety severity.": "ચિંતાની ગંભીરતા માટે પ્રમાણિત ક્લિનિકલ મૂલ્યાંકન.",
    "Adult ADHD (ASRS)": "Adult ADHD (ASRS)",
    "Adult ADHD Self-Report Scale": "Adult ADHD Self-Report Scale",
    "Screening tool for Attention Deficit Hyperactivity Disorder.": "ધ્યાનની ખામી અતિસક્રિયતા વિકાર માટે સ્ક્રીનીંગ સાધન.",
    "PTSD Checklist (PCL-5)": "PTSD Checklist (PCL-5)",
    "PTSD Checklist for DSM-5": "PTSD Checklist for DSM-5",
    "Clinical assessment for Post-Traumatic Stress Disorder.": "પોસ્ટ-ટ્રોમેટિક સ્ટ્રેસ ડિસઓર્ડર માટે ક્લિનિકલ મૂલ્યાંકન.",
    "Bipolar Spectrum": "બાયપોલર સ્પેક્ટ્રમ",
    "Mood Disorder Questionnaire": "Mood Disorder Questionnaire",
    "Screening tool for bipolar spectrum disorders.": "બાયપોલર સ્પેક્ટ્રમ વિકૃતિઓ માટે સ્ક્રીનીંગ સાધન.",
    "OCD Screening": "OCD સ્ક્રીનીંગ",
    "Obsessive-Compulsive Inventory": "Obsessive-Compulsive Inventory",
    "Assessment for symptoms of Obsessive-Compulsive Disorder.": "ઓબ્સેસિવ-કમ્પલ્સિવ ડિસઓર્ડરના લક્ષણો માટે મૂલ્યાંકન.",
    "Attachment Style": "જોડાણ શૈલી",
    "Experiences in Close Relationships": "Experiences in Close Relationships",
    "Assessment of adult attachment styles in relationships.": "સંબંધોમાં પુખ્ત જોડાણ શૈલીઓનું મૂલ્યાંકન.",
    "Burnout Inventory": "બર્નઆઉટ ઇન્વેન્ટરી",
    "Maslach Burnout Inventory": "Maslach Burnout Inventory",
    "Standardized measure of occupational burnout.": "વ્યવસાયિક બર્નઆઉટનું પ્રમાણિત માપ.",
    "Self-Esteem Index": "આત્મસન્માન સૂચકાંક",
    "Rosenberg Self-Esteem Scale": "Rosenberg Self-Esteem Scale",
    "Measure of global self-worth and self-esteem.": "વૈશ્વિક સ્વ-મૂલય અને આત્મસન્માનનું માપ.",
    "Anger Management": "ગુસ્સો વ્યવસ્થાપન",
    "Buss-Perry Aggression Questionnaire": "Buss-Perry Aggression Questionnaire",
    "Clinical measure of aggressive and angry behavior.": "આક્રમક અને ગુસ્સાવાળા વર્તનનું ક્લિનિકલ માપ.",
    "Relationship Satisfaction": "સંબંધ સંતોષ",
    "Couples Satisfaction Index": "Couples Satisfaction Index",
    "Measure of satisfaction in romantic relationships.": "રોમેન્ટિક સંબંધોમાં સંતોષનું માપ.",
    "Sleep Quality": "ઊંઘની ગુણવત્તા",
    "Pittsburgh Sleep Quality Index": "Pittsburgh Sleep Quality Index",
    "Clinical assessment of sleep quality and patterns.": "ઊંઘની ગુણવત્તા અને પેટર્નનું ક્લિનિકલ મૂલ્યાંકન.",
    "Question": "પ્રશ્ન",
    "of": "ના",
    "Over the last 2 weeks": "છેલ્લા 2 અઠવાડિયામાં",
    "Not at all": "બિલકુલ નહીં",
    "Several days": "ઘણા દિવસો",
    "More than half the days": "અડધાથી વધુ દિવસો",
    "Nearly every day": "લગભગ દરરોજ",
    "Minimal Depression": "ન્યૂનતમ ડિપ્રેશન",
    "Mild Depression": "હળવું ડિપ્રેશન",
    "Moderate Depression": "મધ્યમ ડિપ્રેશન",
    "Moderately Severe Depression": "મધ્યમ ગંભીર ડિપ્રેશન",
    "Severe Depression": "ગંભીર ડિપ્રેશન",
    "Minimal Anxiety": "ન્યૂનતમ ચિંતા",
    "Mild Anxiety": "હળવી ચિંતા",
    "Moderate Anxiety": "મધ્યમ ચિંતા",
    "Severe Anxiety": "ગંભીર ચિંતા",
    "Premium Assessment": "પ્રીમિયમ મૂલ્યાંકન",
    "Create a free account to unlock this clinical assessment and track your results.": "આ ક્લિનિકલ મૂલ્યાંકનને અનલૉક કરવા અને તમારા પરિણામોને ટ્રૅક કરવા માટે મફત ખાતું બનાવો.",
    "Unlock Assessment": "મૂલ્યાંકન અનલૉક કરો",
    "Assessment Complete": "મૂલ્યાંકન પૂર્ણ",
    "This is a screening tool, not a diagnosis. To discuss these results, please consult a clinical psychologist.": "આ એક સ્ક્રિનિંગ ટૂલ છે, નિદાન નથી. આ પરિણામોની ચર્ચા કરવા માટે, કૃપા કરીને clinical psychologist ની સલાહ લો.",
    "Discuss with a Counsellor": "Counsellor સાથે ચર્ચા કરો",
    "Retake Assessment": "ફરીથી મૂલ્યાંકન લો",
    "The Top 1%": "ટોચના 1%",
    "Meet Your Match.": "તમારા મેચને મળો.",
    "All Experts": "All Experts",
    "Clinical Psychologists": "Clinical Psychologists",
    "Trauma Specialists": "Trauma Specialists",
    "Relationship Counsellors": "Relationship Counsellors",
    "Child Psychologists": "Child Psychologists",
    "Book": "બુક કરો",
    "12+ Years Exp": "12+ Years Exp",
    "8+ Years Exp": "8+ Years Exp",
    "5+ Years Exp": "5+ Years Exp",
    "15+ Years Exp": "15+ Years Exp",
    "CLINICAL PSYCHOLOGIST": "CLINICAL PSYCHOLOGIST",
    "RELATIONSHIP COUNSELLOR": "RELATIONSHIP COUNSELLOR",
    "TRAUMA SPECIALIST": "TRAUMA SPECIALIST",
    "CHILD PSYCHOLOGIST": "CHILD PSYCHOLOGIST",
    "Sign up instantly. Your data is encrypted and completely confidential.": "તરત જ સાઇન અપ કરો. તમારો ડેટા એન્ક્રિપ્ટેડ અને સંપૂર્ણપણે ગુપ્ત છે.",
    "Feeling nervous, anxious, or on edge?": "ગભરાટ, ચિંતા અથવા બેચેની અનુભવવી?",
    "Not being able to stop or control worrying?": "ચિંતા કરવાનું બંધ કે નિયંત્રિત કરવામાં અસમર્થ હોવું?",
    "Worrying too much about different things?": "વિવિધ બાબતો વિશે વધુ પડતી ચિંતા કરવી?",
    "Trouble relaxing?": "આરામ કરવામાં મુશ્કેલી?",
    "Being so restless that it is hard to sit still?": "એટલા બેચેન હોવું કે શાંત બેસવું મુશ્કેલ બને?",
    "Becoming easily annoyed or irritable?": "સરળતાથી ગુસ્સે અથવા ચીડિયા થઈ જવું?",
    "Feeling afraid as if something awful might happen?": "ડર લાગવો કે જાણે કંઈક ભયંકર થવાનું છે?",
    "Little interest or pleasure in doing things?": "કામો કરવામાં ખૂબ ઓછો રસ અથવા આનંદ હોવો?",
    "Feeling down, depressed, or hopeless?": "ઉદાસી, હતાશા અથવા લાચારી અનુભવવી?",
    "Trouble falling or staying asleep, or sleeping too much?": "ઊંઘવામાં અથવા ઊંઘ ચાલુ રાખવામાં મુશ્કેલી, અથવા વધુ પડતું ઊંઘવું?",
    "Feeling tired or having little energy?": "થાક લાગવો અથવા ઊર્જાનો અભાવ અનુભવવો?",
    "Poor appetite or overeating?": "ભૂખ ન લાગવી અથવા વધુ પડતું ખાવું?",
    "Feeling bad about yourself - or that you are a failure or have let yourself or your family down?": "તમારી જાત વિશે ખરાબ લાગવું - અથવા કે તમે નિષ્ફળ છો અથવા તમારી જાતને કે તમારા પરિવારને નિરાશ કર્યો છે?",
    "Trouble concentrating on things, such as reading the newspaper or watching television?": "વસ્તુઓ પર ધ્યાન કેન્દ્રિત કરવામાં મુશ્કેલી, જેમ કે અખબાર વાંચવું અથવા ટેલિવિઝન જોવું?",
    "Moving or speaking so slowly that other people could have noticed? Or the opposite - being so fidgety or restless that you have been moving around a lot more than usual?": "એટલી ધીમી ગતિએ ચાલવું કે બોલવું કે અન્ય લોકો નોંધ લઈ શકે? અથવા તેનાથી વિપરિત - એટલા બેચેન અથવા અશાંત હોવું કે તમે સામાન્ય કરતાં વધુ ફરી રહ્યા છો?",
    "Thoughts that you would be better off dead, or of hurting yourself in some way?": "એવો વિચાર આવવો કે મરી જવું વધુ સારું રહેશે, અથવા કોઈક રીતે તમારી જાતને નુકસાન પહોંચાડવું?"`;

const paKeys = `\n    "Simple Process": "ਸਰਲ ਪ੍ਰਕਿਰਿਆ",
    "Choose Your Path": "ਆਪਣਾ ਰਸਤਾ ਚੁਣੋ",
    "Start a free session with our clinical AI, or browse our directory of human experts.": "ਸਾਡੇ ਕਲੀਨਿਕਲ AI ਨਾਲ ਇੱਕ ਮੁਫ਼ਤ ਸੈਸ਼ਨ ਸ਼ੁਰੂ ਕਰੋ, ਜਾਂ ਸਾਡੇ ਮਨੁੱਖੀ ਮਾਹਰਾਂ ਦੀ ਡਾਇਰੈਕਟਰੀ ਬ੍ਰਾਊਜ਼ ਕਰੋ।",
    "Begin Healing": "ਠੀਕ ਹੋਣਾ ਸ਼ੁਰੂ ਕਰੋ",
    "Use the CBT diary, take psych tests, and track your mood daily to see real progress.": "ਅਸਲ ਤਰੱਕੀ ਦੇਖਣ ਲਈ CBT ਡਾਇਰੀ ਦੀ ਵਰਤੋਂ ਕਰੋ, ਮਨੋਵਿਗਿਆਨਕ ਟੈਸਟ ਲਓ ਅਤੇ ਰੋਜ਼ਾਨਾ ਆਪਣੇ ਮੂਡ ਨੂੰ ਟ੍ਰੈਕ ਕਰੋ।",
    "For Professionals": "For Professionals",
    "Join India's Top Network of Mental Health Experts": "Join India's Top Network of Mental Health Experts",
    "Expand your practice, manage appointments seamlessly, and help thousands of users on MindHeal. Our streamlined onboarding takes less than 10 minutes.": "ਆਪਣੇ ਅਭਿਆਸ ਦਾ ਵਿਸਤਾਰ ਕਰੋ, ਮੁਲਾਕਾਤਾਂ ਨੂੰ ਨਿਰਵਿਘਨ ਪ੍ਰਬੰਧਿਤ ਕਰੋ, ਅਤੇ MindHeal 'ਤੇ ਹਜ਼ਾਰਾਂ ਉਪਭੋਗਤਾਵਾਂ ਦੀ ਮਦਦ ਕਰੋ। ਸਾਡੀ ਸੁਚਾਰੂ ਆਨਬੋਰਡਿੰਗ ਵਿੱਚ 10 ਮਿੰਟ ਤੋਂ ਘੱਟ ਸਮਾਂ ਲੱਗਦਾ ਹੈ।",
    "Sign Up as Counsellor": "Sign Up as Counsellor",
    "Quick Onboarding": "ਤੁਰੰਤ ਆਨਬੋਰਡਿੰਗ",
    "Verify your RCI credentials and set your availability instantly.": "ਆਪਣੇ RCI ਪ੍ਰਮਾਣ ਪੱਤਰਾਂ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ ਅਤੇ ਆਪਣੀ ਉਪਲਬਧਤਾ ਤੁਰੰਤ ਸੈੱਟ ਕਰੋ।",
    "Smart Scheduling": "ਸਮਾਰਟ ਸ਼ਡਿਊਲਿੰਗ",
    "Manage bookings and reminders with our built-in calendar.": "ਸਾਡੇ ਬਿਲਟ-ਇਨ ਕੈਲੰਡਰ ਨਾਲ ਬੁਕਿੰਗ ਅਤੇ ਰੀਮਾਈਂਡਰ ਪ੍ਰਬੰਧਿਤ ਕਰੋ।",
    "Grow Your Practice": "ਆਪਣਾ ਅਭਿਆਸ ਵਧਾਓ",
    "Get connected with users actively seeking your expertise.": "ਉਹਨਾਂ ਉਪਭੋਗਤਾਵਾਂ ਨਾਲ ਜੁੜੋ ਜੋ ਤੁਹਾਡੀ ਮੁਹਾਰਤ ਦੀ ਸਰਗਰਮੀ ਨਾਲ ਭਾਲ ਕਰ ਰਹੇ ਹਨ।",
    "Real People. Real Healing.": "ਅਸਲੀ ਲੋਕ। ਅਸਲੀ ਇਲਾਜ।",
    "Average App Rating": "Average App Rating",
    "Messages Exchanged": "ਸੰਦੇਸ਼ਾਂ ਦਾ ਆਦਾਨ-ਪ੍ਰਦਾਨ",
    "Report Reduced Anxiety": "ਘਟੀ ਹੋਈ ਚਿੰਤਾ ਦੀ ਰਿਪੋਰਟ",
    "I struggled with severe anxiety for years. The CBT tools and my therapist on MindHeal completely changed my life.": "ਮੈਂ ਸਾਲਾਂ ਤੱਕ ਗੰਭੀਰ ਚਿੰਤਾ ਨਾਲ ਸੰਘਰਸ਼ ਕੀਤਾ। CBT ਟੂਲਸ ਅਤੇ MindHeal 'ਤੇ ਮੇਰੇ ਥੈਰੇਪਿਸਟ ਨੇ ਮੇਰੀ ਜ਼ਿੰਦਗੀ ਪੂਰੀ ਤਰ੍ਹਾਂ ਬਦਲ ਦਿੱਤੀ।",
    "The AI companion is incredible for late-night panic attacks. It grounds me instantly.": "ਦੇਰ ਰਾਤ ਦੇ ਪੈਨਿਕ ਅਟੈਕ ਲਈ AI ਸਾਥੀ ਸ਼ਾਨਦਾਰ ਹੈ। ਇਹ ਮੈਨੂੰ ਤੁਰੰਤ ਸ਼ਾਂਤ ਕਰਦਾ ਹੈ।",
    "Finally, a platform that understands Indian cultural context. My therapist here gets exactly what I mean without me over-explaining.": "ਆਖਰਕਾਰ, ਇੱਕ ਪਲੇਟਫਾਰਮ ਜੋ ਭਾਰਤੀ ਸੱਭਿਆਚਾਰਕ ਸੰਦਰਭ ਨੂੰ ਸਮਝਦਾ ਹੈ। ਇੱਥੇ ਮੇਰਾ ਥੈਰੇਪਿਸਟ ਮੇਰੇ ਬਿਨਾਂ ਜ਼ਿਆਦਾ ਸਮਝਾਏ ਬਿਲਕੁਲ ਸਮਝ ਜਾਂਦਾ ਹੈ ਕਿ ਮੇਰਾ ਕੀ ਮਤਲਬ ਹੈ।",
    "Know Thyself": "ਆਪਣੇ ਆਪ ਨੂੰ ਜਾਣੋ",
    "12 Free Clinical Tests.": "12 ਮੁਫ਼ਤ ਕਲੀਨਿਕਲ ਟੈਸਟ",
    "Available Assessments": "ਉਪਲਬਧ ਮੁਲਾਂਕਣ",
    "PHQ-9 (Depression)": "PHQ-9 (Depression)",
    "Patient Health Questionnaire": "Patient Health Questionnaire",
    "Standardized clinical assessment for depression severity.": "ਡਿਪਰੈਸ਼ਨ ਦੀ ਗੰਭੀਰਤਾ ਲਈ ਮਿਆਰੀ ਕਲੀਨਿਕਲ ਮੁਲਾਂਕਣ।",
    "GAD-7 (Anxiety)": "GAD-7 (Anxiety)",
    "Generalized Anxiety Disorder Assessment": "Generalized Anxiety Disorder Assessment",
    "Standardized clinical assessment for anxiety severity.": "ਚਿੰਤਾ ਦੀ ਗੰਭੀਰਤਾ ਲਈ ਮਿਆਰੀ ਕਲੀਨਿਕਲ ਮੁਲਾਂਕਣ।",
    "Adult ADHD (ASRS)": "Adult ADHD (ASRS)",
    "Adult ADHD Self-Report Scale": "Adult ADHD Self-Report Scale",
    "Screening tool for Attention Deficit Hyperactivity Disorder.": "ਧਿਆਨ ਦੀ ਘਾਟ ਹਾਈਪਰਐਕਟੀਵਿਟੀ ਵਿਕਾਰ ਲਈ ਸਕ੍ਰੀਨਿੰਗ ਟੂਲ।",
    "PTSD Checklist (PCL-5)": "PTSD Checklist (PCL-5)",
    "PTSD Checklist for DSM-5": "PTSD Checklist for DSM-5",
    "Clinical assessment for Post-Traumatic Stress Disorder.": "ਪੋਸਟ-ਟਰਾਮੈਟਿਕ ਤਣਾਅ ਵਿਕਾਰ ਲਈ ਕਲੀਨਿਕਲ ਮੁਲਾਂਕਣ।",
    "Bipolar Spectrum": "ਬਾਈਪੋਲਰ ਸਪੈਕਟ੍ਰਮ",
    "Mood Disorder Questionnaire": "Mood Disorder Questionnaire",
    "Screening tool for bipolar spectrum disorders.": "ਬਾਈਪੋਲਰ ਸਪੈਕਟ੍ਰਮ ਵਿਕਾਰ ਲਈ ਸਕ੍ਰੀਨਿੰਗ ਟੂਲ।",
    "OCD Screening": "OCD ਸਕ੍ਰੀਨਿੰਗ",
    "Obsessive-Compulsive Inventory": "Obsessive-Compulsive Inventory",
    "Assessment for symptoms of Obsessive-Compulsive Disorder.": "Obsessive-Compulsive Disorder ਦੇ ਲੱਛਣਾਂ ਲਈ ਮੁਲਾਂਕਣ।",
    "Attachment Style": "ਲਗਾਵ ਸ਼ੈਲੀ",
    "Experiences in Close Relationships": "Experiences in Close Relationships",
    "Assessment of adult attachment styles in relationships.": "ਰਿਸ਼ਤਿਆਂ ਵਿੱਚ ਬਾਲਗ ਲਗਾਵ ਸ਼ੈਲੀਆਂ ਦਾ ਮੁਲਾਂਕਣ।",
    "Burnout Inventory": "ਬਰਨਆਉਟ ਇਨਵੈਂਟਰੀ",
    "Maslach Burnout Inventory": "Maslach Burnout Inventory",
    "Standardized measure of occupational burnout.": "ਵਿਵਸਾਇਕ ਬਰਨਆਉਟ ਦਾ ਮਿਆਰੀ ਮਾਪ।",
    "Self-Esteem Index": "ਸਵੈ-ਮਾਣ ਸੂਚਕਾਂਕ",
    "Rosenberg Self-Esteem Scale": "Rosenberg Self-Esteem Scale",
    "Measure of global self-worth and self-esteem.": "ਗਲੋਬਲ ਸਵੈ-ਮਾਣ ਅਤੇ ਸਵੈ-ਮਾਣ ਦਾ ਮਾਪ।",
    "Anger Management": "ਗੁੱਸਾ ਪ੍ਰਬੰਧਨ",
    "Buss-Perry Aggression Questionnaire": "Buss-Perry Aggression Questionnaire",
    "Clinical measure of aggressive and angry behavior.": "ਹਮਲਾਵਰ ਅਤੇ ਗੁੱਸੇ ਵਾਲੇ ਵਿਵਹਾਰ ਦਾ ਕਲੀਨਿਕਲ ਮਾਪ।",
    "Relationship Satisfaction": "ਰਿਸ਼ਤੇ ਦੀ ਸੰਤੁਸ਼ਟੀ",
    "Couples Satisfaction Index": "Couples Satisfaction Index",
    "Measure of satisfaction in romantic relationships.": "ਰੋਮਾਂਟਿਕ ਰਿਸ਼ਤਿਆਂ ਵਿੱਚ ਸੰਤੁਸ਼ਟੀ ਦਾ ਮਾਪ।",
    "Sleep Quality": "ਨੀਂਦ ਦੀ ਗੁਣਵੱਤਾ",
    "Pittsburgh Sleep Quality Index": "Pittsburgh Sleep Quality Index",
    "Clinical assessment of sleep quality and patterns.": "ਨੀਂਦ ਦੀ ਗੁਣਵੱਤਾ ਅਤੇ ਪੈਟਰਨਾਂ ਦਾ ਕਲੀਨਿਕਲ ਮੁਲਾਂਕਣ।",
    "Question": "ਸਵਾਲ",
    "of": "ਦਾ",
    "Over the last 2 weeks": "ਪਿਛਲੇ 2 ਹਫ਼ਤਿਆਂ ਵਿੱਚ",
    "Not at all": "ਬਿਲਕੁਲ ਨਹੀਂ",
    "Several days": "ਕਈ ਦਿਨ",
    "More than half the days": "ਅੱਧੇ ਤੋਂ ਵੱਧ ਦਿਨ",
    "Nearly every day": "ਲਗਭਗ ਹਰ ਦਿਨ",
    "Minimal Depression": "ਘੱਟੋ-ਘੱਟ ਡਿਪਰੈਸ਼ਨ",
    "Mild Depression": "ਹਲਕਾ ਡਿਪਰੈਸ਼ਨ",
    "Moderate Depression": "ਦਰਮਿਆਨਾ ਡਿਪਰੈਸ਼ਨ",
    "Moderately Severe Depression": "ਦਰਮਿਆਨਾ ਗੰਭੀਰ ਡਿਪਰੈਸ਼ਨ",
    "Severe Depression": "ਗੰਭੀਰ ਡਿਪਰੈਸ਼ਨ",
    "Minimal Anxiety": "ਘੱਟੋ-ਘੱਟ ਚਿੰਤਾ",
    "Mild Anxiety": "ਹਲਕੀ ਚਿੰਤਾ",
    "Moderate Anxiety": "ਦਰਮਿਆਨੀ ਚਿੰਤਾ",
    "Severe Anxiety": "ਗੰਭੀਰ ਚਿੰਤਾ",
    "Premium Assessment": "ਪ੍ਰੀਮੀਅਮ ਮੁਲਾਂਕਣ",
    "Create a free account to unlock this clinical assessment and track your results.": "ਇਸ ਕਲੀਨਿਕਲ ਮੁਲਾਂਕਣ ਨੂੰ ਅਨਲੌਕ ਕਰਨ ਅਤੇ ਆਪਣੇ ਨਤੀਜਿਆਂ ਨੂੰ ਟਰੈਕ ਕਰਨ ਲਈ ਇੱਕ ਮੁਫਤ ਖਾਤਾ ਬਣਾਓ।",
    "Unlock Assessment": "ਮੁਲਾਂਕਣ ਨੂੰ ਅਨਲੌਕ ਕਰੋ",
    "Assessment Complete": "ਮੁਲਾਂਕਣ ਪੂਰਾ ਹੋਇਆ",
    "This is a screening tool, not a diagnosis. To discuss these results, please consult a clinical psychologist.": "ਇਹ ਇੱਕ ਸਕ੍ਰੀਨਿੰਗ ਟੂਲ ਹੈ, ਕੋਈ ਨਿਦਾਨ ਨਹੀਂ। ਇਹਨਾਂ ਨਤੀਜਿਆਂ 'ਤੇ ਚਰਚา ਕਰਨ ਲਈ, ਕਿਰਪਾ ਕਰਕੇ clinical psychologist ਨਾਲ ਸਲਾਹ ਕਰੋ।",
    "Discuss with a Counsellor": "Counsellor ਨਾਲ ਚਰਚਾ ਕਰੋ",
    "Retake Assessment": "ਮੁਲਾਂਕਣ ਦੁਬਾਰਾ ਲਓ",
    "The Top 1%": "ਚੋਟੀ ਦੇ 1%",
    "Meet Your Match.": "ਆਪਣਾ ਮੇਲ ਲੱਭੋ।",
    "All Experts": "All Experts",
    "Clinical Psychologists": "Clinical Psychologists",
    "Trauma Specialists": "Trauma Specialists",
    "Relationship Counsellors": "Relationship Counsellors",
    "Child Psychologists": "Child Psychologists",
    "Book": "ਬੁੱਕ ਕਰੋ",
    "12+ Years Exp": "12+ Years Exp",
    "8+ Years Exp": "8+ Years Exp",
    "5+ Years Exp": "5+ Years Exp",
    "15+ Years Exp": "15+ Years Exp",
    "CLINICAL PSYCHOLOGIST": "CLINICAL PSYCHOLOGIST",
    "RELATIONSHIP COUNSELLOR": "RELATIONSHIP COUNSELLOR",
    "TRAUMA SPECIALIST": "TRAUMA SPECIALIST",
    "CHILD PSYCHOLOGIST": "CHILD PSYCHOLOGIST",
    "Sign up instantly. Your data is encrypted and completely confidential.": "ਤੁਰੰਤ ਸਾਈਨ ਅੱਪ ਕਰੋ। ਤੁਹਾਡਾ ਡੇਟਾ ਐਨਕ੍ਰਿਪਟਡ ਅਤੇ ਪੂਰੀ ਤਰ੍ਹਾਂ ਗੁਪत ਹੈ।",
    "Feeling nervous, anxious, or on edge?": "ਘਬਰਾਹਟ, ਚਿੰਤਾ, ਜਾਂ ਬੇਚੈਨੀ ਮਹਿਸੂਸ ਹੋ ਰਹੀ ਹੈ?",
    "Not being able to stop or control worrying?": "ਚਿੰਤਾ ਕਰਨਾ ਬੰਦ ਜਾਂ ਕਾਬੂ ਕਰਨ ਵਿੱਚ ਅਸਮਰੱਥ ਹੋਣਾ?",
    "Worrying too much about different things?": "ਵੱਖ-ਵੱਖ ਚੀਜ਼ਾਂ ਬਾਰੇ ਬਹੁਤ ਜ਼ਿਆਦਾ ਚਿੰਤਾ ਕਰਨਾ?",
    "Trouble relaxing?": "ਆਰਾਮ ਕਰਨ ਵਿੱਚ ਮੁਸ਼ਕਲ?",
    "Being so restless that it is hard to sit still?": "ਇੰਨਾ ਬੇਚੈਨ ਹੋਣਾ ਕਿ ਚੁੱਪਚਾਪ ਬੈਠਣਾ ਮੁਸ਼ਕਲ ਹੋਵੇ?",
    "Becoming easily annoyed or irritable?": "ਆਸਾਨੀ ਨਾਲ ਗੁੱਸੇ ਜਾਂ ਚਿੜਚਿੜੇ ਹੋਣਾ?",
    "Feeling afraid as if something awful might happen?": "ਡਰ ਮਹਿਸੂਸ ਹੋਣਾ ਜਿਵੇਂ ਕੁਝ ਭਿਆਨਕ ਵਾਪਰਨ ਵਾਲਾ ਹੈ?",
    "Little interest or pleasure in doing things?": "ਕੰਮ ਕਰਨ ਵਿੱਚ ਬਹੁਤ ਘੱਟ ਦਿਲਚਸਪੀ ਜਾਂ ਖੁਸ਼ੀ ਹੋਣੀ?",
    "Feeling down, depressed, or hopeless?": "ਉਦਾਸ, ਨਿਰਾਸ਼, ਜਾਂ ਬੇਬੱਸ ਮਹਿਸੂਸ ਕਰਨਾ?",
    "Trouble falling or staying asleep, or sleeping too much?": "ਨੀਂਦ ਆਉਣ ਜਾਂ ਸੌਣ ਵਿੱਚ ਮੁਸ਼ਕਲ, ਜਾਂ ਬਹੁਤ ਜ਼ਿਆਦਾ ਸੌਣਾ?",
    "Feeling tired or having little energy?": "ਥਕਾਵਟ ਜਾਂ ਘੱਟ ਊਰਜਾ ਮਹਿਸੂਸ ਹੋਣਾ?",
    "Poor appetite or overeating?": "ਭੁੱਖ ਨਾ ਲੱਗਣਾ ਜਾਂ ਬਹੁਤ ਜ਼ਿਆਦਾ ਖਾਣਾ?",
    "Feeling bad about yourself - or that you are a failure or have let yourself or your family down?": "ਆਪਣੇ ਬਾਰੇ ਬੁਰਾ ਮਹਿਸੂਸ ਕਰਨਾ - ਜਾਂ ਇਹ ਕਿ ਤੁਸੀਂ ਇੱਕ ਅਸਫਲਤਾ ਹੋ ਜਾਂ ਆਪਣੇ ਆਪ ਨੂੰ ਜਾਂ ਆਪਣੇ ਪਰਿਵਾਰ ਨੂੰ ਨਿਰਾਸ਼ ਕੀਤਾ ਹੈ?",
    "Trouble concentrating on things, such as reading the newspaper or watching television?": "ਚੀਜ਼ਾਂ 'ਤੇ ਧਿਆਨ ਕੇਂਦਰਿਤ ਕਰਨ ਵਿੱਚ ਮੁਸ਼ਕल, ਜਿਵੇਂ ਕਿ ਅਖ਼ਬਾਰ ਪੜ੍ਹਨਾ ਜਾਂ ਟੈਲੀਵਿਜ਼ਨ ਦੇਖਣਾ?",
    "Moving or speaking so slowly that other people could have noticed? Or the opposite - being so fidgety or restless that you have been moving around a lot more than usual?": "ਇੰਨੀ ਹੌਲੀ ਹੌਲੀ ਚੱਲਣਾ ਜਾਂ ਬੋਲਣਾ ਕਿ ਦੂਜੇ ਲੋਕ ਨੋਟਿਸ ਕਰ ਸਕਣ? ਜਾਂ ਇਸਦੇ ਉਲਟ - ਇੰਨਾ ਬੇਚੈਨ ਹੋਣਾ ਕਿ ਤੁਸੀਂ ਆਮ ਨਾਲੋਂ ਜ਼ਿਆદા ਘੁੰਮ ਰਹੇ ਹੋ?",
    "Thoughts that you would be better off dead, or of hurting yourself in some way?": "ਇਹ ਵਿਚਾਰ ਆਉਣਾ ਕਿ ਮਰ ਜਾਣਾ ਬਿਹਤਰ ਹੋਵੇਗਾ, ਜਾਂ ਕਿਸੇ ਤਰੀਕੇ ਨਾਲ ਆਪਣੇ ਆਪ ਨੂੰ ਨੁਕਸਾਨ ਪਹੁੰਚਾਉਣਾ?"`;

const arKeys = `\n    "Simple Process": "عملية بسيطة",
    "Choose Your Path": "اختر طريقك",
    "Start a free session with our clinical AI, or browse our directory of human experts.": "ابدأ جلسة مجانية مع الذكاء الاصطناعي السريري لدينا، أو تصفح دليلنا للخبراء البشر.",
    "Begin Healing": "ابدأ التعافي",
    "Use the CBT diary, take psych tests, and track your mood daily to see real progress.": "استخدم مفكرة CBT، وأجرِ الاختبارات النفسية، وتتبع مزاجك يوميًا لرؤية تقدم حقيقي.",
    "For Professionals": "For Professionals",
    "Join India's Top Network of Mental Health Experts": "Join India's Top Network of Mental Health Experts",
    "Expand your practice, manage appointments seamlessly, and help thousands of users on MindHeal. Our streamlined onboarding takes less than 10 minutes.": "قم بتوسيع نطاق ممارستك، وإدارة المواعيد بسلاسة، ومساعدة آلاف المستخدمين على MindHeal. يستغرق التسجيل المبسط لدينا أقل من 10 دقائق.",
    "Sign Up as Counsellor": "Sign Up as Counsellor",
    "Quick Onboarding": "تسجيل سريع",
    "Verify your RCI credentials and set your availability instantly.": "تحقق من أوراق اعتماد RCI الخاصة بك واضبط تواجدك على الفور.",
    "Smart Scheduling": "جدولة ذكية",
    "Manage bookings and reminders with our built-in calendar.": "إدارة الحجوزات والتذكيرات من خلال تقويمنا المدمج.",
    "Grow Your Practice": "نمِّ ممارستك",
    "Get connected with users actively seeking your expertise.": "تواصل مع المستخدمين الذين يبحثون بنشاط عن خبرتك.",
    "Real People. Real Healing.": "أشخاص حقيقيون. تعافٍ حقيقي.",
    "Average App Rating": "Average App Rating",
    "Messages Exchanged": "الرسائل المتبادلة",
    "Report Reduced Anxiety": "أبلغوا عن انخفاض القلق",
    "I struggled with severe anxiety for years. The CBT tools and my therapist on MindHeal completely changed my life.": "لقد عانيت من القلق الشديد لسنوات. غيرت أدوات العلاج السلوكي المعرفي ومعالجي على MindHeal حياتي تمامًا.",
    "The AI companion is incredible for late-night panic attacks. It grounds me instantly.": "المساعد الذكي رائع لنوبات الهلع في وقت متأخر من الليل. إنه يهدئني على الفور.",
    "Finally, a platform that understands Indian cultural context. My therapist here gets exactly what I mean without me over-explaining.": "أخيرًا، منصة تفهم السياق الثقافي الهندي. يفهم معالجي هنا بالضبط ما أعنيه دون أن أفرط في الشرح.",
    "Know Thyself": "اعرف نفسك",
    "12 Free Clinical Tests.": "12 اختبارًا سريريًا مجانيًا.",
    "Available Assessments": "التقييمات المتاحة",
    "PHQ-9 (Depression)": "PHQ-9 (Depression)",
    "Patient Health Questionnaire": "Patient Health Questionnaire",
    "Standardized clinical assessment for depression severity.": "تقييم سريري موحد لشدة الاكتئاب.",
    "GAD-7 (Anxiety)": "GAD-7 (Anxiety)",
    "Generalized Anxiety Disorder Assessment": "Generalized Anxiety Disorder Assessment",
    "Standardized clinical assessment for anxiety severity.": "تقييم سريري موحد لشدة القلق.",
    "Adult ADHD (ASRS)": "Adult ADHD (ASRS)",
    "Adult ADHD Self-Report Scale": "Adult ADHD Self-Report Scale",
    "Screening tool for Attention Deficit Hyperactivity Disorder.": "أداة فحص لاضطراب فرط الحركة ونقص الانتباه.",
    "PTSD Checklist (PCL-5)": "PTSD Checklist (PCL-5)",
    "PTSD Checklist for DSM-5": "PTSD Checklist for DSM-5",
    "Clinical assessment for Post-Traumatic Stress Disorder.": "التقييم السريري لاضطراب ما بعد الصدمة.",
    "Bipolar Spectrum": "طيف ثنائي القطب",
    "Mood Disorder Questionnaire": "Mood Disorder Questionnaire",
    "Screening tool for bipolar spectrum disorders.": "أداة فحص لاضطرابات طيف ثنائي القطب.",
    "OCD Screening": "فحص الوسواس القهري",
    "Obsessive-Compulsive Inventory": "Obsessive-Compulsive Inventory",
    "Assessment for symptoms of Obsessive-Compulsive Disorder.": "تقييم أعراض اضطراب الوسواس القهري.",
    "Attachment Style": "نمط التعلق",
    "Experiences in Close Relationships": "Experiences in Close Relationships",
    "Assessment of adult attachment styles in relationships.": "تقييم أنماط تعلق البالغين في العلاقات.",
    "Burnout Inventory": "مخزون الاحتراق النفسي",
    "Maslach Burnout Inventory": "Maslach Burnout Inventory",
    "Standardized measure of occupational burnout.": "مقياس موحد للاحتراق المهني.",
    "Self-Esteem Index": "مؤشر تقدير الذات",
    "Rosenberg Self-Esteem Scale": "Rosenberg Self-Esteem Scale",
    "Measure of global self-worth and self-esteem.": "مقياس تقدير الذات العام.",
    "Anger Management": "إدارة الغضب",
    "Buss-Perry Aggression Questionnaire": "Buss-Perry Aggression Questionnaire",
    "Clinical measure of aggressive and angry behavior.": "مقياس سريري للسلوك العدواني والغاضب.",
    "Relationship Satisfaction": "الرضا عن العلاقة",
    "Couples Satisfaction Index": "Couples Satisfaction Index",
    "Measure of satisfaction in romantic relationships.": "مقياس الرضا في العلاقات الرومانسية.",
    "Sleep Quality": "جودة النوم",
    "Pittsburgh Sleep Quality Index": "Pittsburgh Sleep Quality Index",
    "Clinical assessment of sleep quality and patterns.": "التقييم السريري لجودة وأنماط النوم.",
    "Question": "سؤال",
    "of": "من",
    "Over the last 2 weeks": "خلال الأسبوعين الماضيين",
    "Not at all": "على الإطلاق",
    "Several days": "عدة أيام",
    "More than half the days": "أكثر من نصف الأيام",
    "Nearly every day": "كل يوم تقريبًا",
    "Minimal Depression": "اكتئاب طفيف",
    "Mild Depression": "اكتئاب خفيف",
    "Moderate Depression": "اكتئاب معتدل",
    "Moderately Severe Depression": "اكتئاب شديد نسبيًا",
    "Severe Depression": "اكتئاب شديد",
    "Minimal Anxiety": "قلق طفيف",
    "Mild Anxiety": "قلق خفيف",
    "Moderate Anxiety": "قلق معتدل",
    "Severe Anxiety": "قلق شديد",
    "Premium Assessment": "تقييم مميز",
    "Create a free account to unlock this clinical assessment and track your results.": "أنشئ حسابًا مجانيًا لفتح هذا التقييم السريري وتتبع نتائجك.",
    "Unlock Assessment": "فتح التقييم",
    "Assessment Complete": "اكتمل التقييم",
    "This is a screening tool, not a diagnosis. To discuss these results, please consult a clinical psychologist.": "هذه أداة فحص وليست تشخيصًا. لمناقشة هذه النتائج، يرجى استشارة clinical psychologist.",
    "Discuss with a Counsellor": "Discuss with a Counsellor",
    "Retake Assessment": "إعادة التقييم",
    "The Top 1%": "أفضل 1%",
    "Meet Your Match.": "ابحث عن نصفك الآخر.",
    "All Experts": "All Experts",
    "Clinical Psychologists": "Clinical Psychologists",
    "Trauma Specialists": "Trauma Specialists",
    "Relationship Counsellors": "Relationship Counsellors",
    "Child Psychologists": "Child Psychologists",
    "Book": "احجز",
    "12+ Years Exp": "12+ Years Exp",
    "8+ Years Exp": "8+ Years Exp",
    "5+ Years Exp": "5+ Years Exp",
    "15+ Years Exp": "15+ Years Exp",
    "CLINICAL PSYCHOLOGIST": "CLINICAL PSYCHOLOGIST",
    "RELATIONSHIP COUNSELLOR": "RELATIONSHIP COUNSELLOR",
    "TRAUMA SPECIALIST": "TRAUMA SPECIALIST",
    "CHILD PSYCHOLOGIST": "CHILD PSYCHOLOGIST",
    "Sign up instantly. Your data is encrypted and completely confidential.": "سجل فورًا. بياناتك مشفرة وسرية تمامًا.",
    "Feeling nervous, anxious, or on edge?": "الشعور بالعصبية أو القلق أو التوتر؟",
    "Not being able to stop or control worrying?": "عدم القدرة على التوقف عن القلق أو السيطرة عليه؟",
    "Worrying too much about different things?": "القلق الزائد بشأن أشياء مختلفة؟",
    "Trouble relaxing?": "صعوبة في الاسترخاء؟",
    "Being so restless that it is hard to sit still?": "الشعور بعدم الهدوء لدرجة يصعب معها الجلوس ساكنًا؟",
    "Becoming easily annoyed or irritable?": "الغضب السريع أو سرعة الانفعال؟",
    "Feeling afraid as if something awful might happen?": "الشعور بالخوف وكأن شيئًا فظيعًا قد يحدث؟",
    "Little interest or pleasure in doing things?": "اهتمام أو متعة ضئيلة في القيام بالأشياء؟",
    "Feeling down, depressed, or hopeless?": "الشعور بالاحباط أو الاكتئاب أو اليأس؟",
    "Trouble falling or staying asleep, or sleeping too much?": "صعوبة في النوم أو الاستمرار فيه، أو النوم الزائد؟",
    "Feeling tired or having little energy?": "الشعور بالتعب أو قلة الطاقة؟",
    "Poor appetite or overeating?": "ضعف الشهية أو الإفراط في تناول الطعام؟",
    "Feeling bad about yourself - or that you are a failure or have let yourself or your family down?": "الشعور بالسوء تجاه نفسك - أو أنك فاشل أو خيبت أمل نفسك أو عائلتك؟",
    "Trouble concentrating on things, such as reading the newspaper or watching television?": "صعوبة في التركيز على الأشياء، مثل قراءة الصحف أو مشاهدة التلفزيون؟",
    "Moving or speaking so slowly that other people could have noticed? Or the opposite - being so fidgety or restless that you have been moving around a lot more than usual?": "التحرك أو التحدث ببطء شديد لدرجة قد يلاحظها الآخرون؟ أو العكس - التململ وعدم الاستقرار والتحرك أكثر من المعتاد؟",
    "Thoughts that you would be better off dead, or of hurting yourself in some way?": "أفكار بأن الموت قد يكون أفضل، أو إيذاء نفسك بطريقة ما؟"`;

const splitText = (target, replacement) => {
  const idx = content.indexOf(target);
  if (idx === -1) {
    throw new Error(`Target string not found: ${target}`);
  }
  content = content.slice(0, idx) + target + replacement + content.slice(idx + target.length);
};

splitText(
  '"Your Mental Sanctuary, Anywhere.": "Your Mental Sanctuary, Anywhere.",',
  enKeys
);

splitText(
  '"Your Mental Sanctuary, Anywhere.": "आपका मानसिक अभयारण्य, कहीं भी।",',
  hiKeys
);

splitText(
  '"Your Mental Sanctuary, Anywhere.": "உங்கள் மன சரணாலயம், எங்கும்.",',
  taKeys
);

splitText(
  '"Your Mental Sanctuary, Anywhere.": "మీ మానసిక ప్రశాంతత, ఎక్కడైనా.",',
  teKeys
);

splitText(
  '"Your Mental Sanctuary, Anywhere.": "તમારું માનસિક અભયારણ્ય, ગમે ત્યાં.",',
  guKeys
);

splitText(
  '"Your Mental Sanctuary, Anywhere.": "ਤੁਹਾਡੀ ਮਾਨਸਿਕ ਸ਼ਰਨ, ਕਿਤੇ ਵੀ।",',
  paKeys
);

splitText(
  '"Your Mental Sanctuary, Anywhere.": "ملاذك النفسي، في أي مكان.",',
  arKeys
);

fs.writeFileSync(filePath, content, 'utf8');
console.log("Translation keys successfully added to i18n.js!");
